# Generated by Django 5.0.3 on 2024-05-09 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_todolist_task_todolist_alter_task_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="User",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todolist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
